# Generated by Django 4.2.7 on 2023-12-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image_url',
        ),
        migrations.AddField(
            model_name='report',
            name='image_hash',
            field=models.CharField(default='abcdefg', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='report',
            name='real',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='synthetic',
            field=models.IntegerField(default=0),
        ),
    ]
